services:
  - name: backup-mysql-database
    type: cron
    schedule: "0 3 * * *"
    region: oregon
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MYSQL_HOST
        fromService:
          name: replace-with-name-of-your-mysql-private-service
          type: pserv
          property: host
      - key: MYSQL_DATABASE
        fromService:
          name: replace-with-name-of-your-mysql-private-service
          type: pserv
          envVarKey: MYSQL_DATABASE
      - key: MYSQL_USER
        fromService:
          name: replace-with-name-of-your-mysql-private-service
          type: pserv
          envVarKey: MYSQL_USER
      - key: MYSQL_PASSWORD
        fromService:
          name: replace-with-name-of-your-mysql-private-service
          type: pserv
          envVarKey: MYSQL_PASSWORD
      # pick the region closest to your database
      # For example, us-west-2 for the Oregon region
      - key: AWS_REGION
        sync: false
      # A globally unique name for your bucket
      # For example, <your-username>-<database name>-render-postgres-backups
      - key: S3_BUCKET_NAME
        sync: false
      # Looks like "AKIAXXXXXXXXXXXXXXXX"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      # Postgres version of your MySQL database 
      # For example, 8.0
      - key: MYSQL_VERSION
        sync: false
